# Generated by Django 4.0.8 on 2023-07-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydjobs',
            name='phonenumber',
            field=models.IntegerField(),
        ),
    ]
