# Generated by Django 4.0.8 on 2023-07-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0003_alter_hydjobs_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chennaijobs',
            name='phonenumber',
            field=models.BigIntegerField(),
        ),
    ]
